/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZustandTestRouteImport } from './routes/zustand-test'
import { Route as MswTestRouteImport } from './routes/msw-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbTestIndexRouteImport } from './routes/db-test.index'
import { Route as DbTestIdRouteImport } from './routes/db-test.$id'

const ZustandTestRoute = ZustandTestRouteImport.update({
  id: '/zustand-test',
  path: '/zustand-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MswTestRoute = MswTestRouteImport.update({
  id: '/msw-test',
  path: '/msw-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestIndexRoute = DbTestIndexRouteImport.update({
  id: '/db-test/',
  path: '/db-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestIdRoute = DbTestIdRouteImport.update({
  id: '/db-test/$id',
  path: '/db-test/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
  '/db-test': typeof DbTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
  '/db-test': typeof DbTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
  '/db-test/': typeof DbTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/msw-test' | '/zustand-test' | '/db-test/$id' | '/db-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/msw-test' | '/zustand-test' | '/db-test/$id' | '/db-test'
  id:
    | '__root__'
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/db-test/$id'
    | '/db-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MswTestRoute: typeof MswTestRoute
  ZustandTestRoute: typeof ZustandTestRoute
  DbTestIdRoute: typeof DbTestIdRoute
  DbTestIndexRoute: typeof DbTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zustand-test': {
      id: '/zustand-test'
      path: '/zustand-test'
      fullPath: '/zustand-test'
      preLoaderRoute: typeof ZustandTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msw-test': {
      id: '/msw-test'
      path: '/msw-test'
      fullPath: '/msw-test'
      preLoaderRoute: typeof MswTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test/': {
      id: '/db-test/'
      path: '/db-test'
      fullPath: '/db-test'
      preLoaderRoute: typeof DbTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test/$id': {
      id: '/db-test/$id'
      path: '/db-test/$id'
      fullPath: '/db-test/$id'
      preLoaderRoute: typeof DbTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MswTestRoute: MswTestRoute,
  ZustandTestRoute: ZustandTestRoute,
  DbTestIdRoute: DbTestIdRoute,
  DbTestIndexRoute: DbTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
